version: "2"

services:
  client:
    image: node:12.16.2
    container_name: client
    command: npm run docker
    volumes:
      - ./client:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0

  server:
    image: node:12.16.2
    container_name: server
    command: npm run docker
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    environment:
      DB_HOST: host.docker.internal
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    container_name: db
    env_file:
      - "./db/database.env"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: